server {
    listen 80;
    server_name excalidraw.local;

    root /Users/dwhitehouse/education/excalidraw/excalidraw-app/build;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml image/svg+xml;
}
